// For more info, see https://github.com/storybookjs/eslint-plugin-storybook#configuration-flat-config-format
import storybook from 'eslint-plugin-storybook';
import noRawFormElements from './eslint-rules/no-raw-form-elements.js';
import noUtilitySoup from './eslint-rules/no-utility-soup.js';
import noDuplicateFieldNames from './eslint-rules/no-duplicate-field-names.js';
import noDbTransaction from './eslint-rules/no-db-transaction.js';

import prettier from 'eslint-config-prettier';
import path from 'node:path';
import { includeIgnoreFile } from '@eslint/compat';
import js from '@eslint/js';
import svelte from 'eslint-plugin-svelte';
import { defineConfig } from 'eslint/config';
import globals from 'globals';
import ts from 'typescript-eslint';
import svelteConfig from './svelte.config.js';

const gitignorePath = path.resolve(import.meta.dirname, '.gitignore');

// The `custom` plugin must be registered in exactly one config object — eslint's
// flat config rejects the same plugin namespace appearing in more than one config
// ("Cannot redefine plugin custom"), even with an identical object. So register it
// globally here and let the file-scoped blocks below only *enable* its rules.
const customPlugin = {
	rules: {
		'no-raw-form-elements': noRawFormElements,
		'no-utility-soup': noUtilitySoup,
		'no-duplicate-field-names': noDuplicateFieldNames,
		'no-db-transaction': noDbTransaction
	}
};

export default defineConfig(
	includeIgnoreFile(gitignorePath),
	// Generated by `wrangler types` — not authored source, ships with its own /* eslint-disable */.
	{ ignores: ['worker-configuration.d.ts'] },
	js.configs.recommended,
	ts.configs.recommended,
	svelte.configs.recommended,
	storybook.configs['flat/recommended'],
	prettier,
	svelte.configs.prettier,
	{
		languageOptions: { globals: { ...globals.browser, ...globals.node } },
		rules: {
			// typescript-eslint strongly recommend that you do not use the no-undef lint rule on TypeScript projects.
			// see: https://typescript-eslint.io/troubleshooting/faqs/eslint/#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors
			'no-undef': 'off',
			// Downgraded from the typescript-eslint recommended default (error). The codebase has
			// ~200 pre-existing `any` usages; treat as a warning so it stays visible without
			// blocking CI, to be paid down incrementally rather than in this lint-cleanup pass.
			'@typescript-eslint/no-explicit-any': 'warn',
			// Honour the conventional `_`-prefix for intentionally-unused bindings (e.g.
			// `{#each items as _, i}`, unused catch params). The rule still errors on all
			// other unused identifiers.
			'@typescript-eslint/no-unused-vars': [
				'error',
				{ argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }
			],
			// Downgraded from svelte recommended (error). SvelteKit's typed `resolve()` only accepts
			// statically-known route ids, but this codebase navigates to many runtime/dynamic string
			// paths (generic `href` props on Nav/Button/IdCard/etc., remote `redirectUrl`s, computed
			// nav targets). Wrapping those in `resolve()` produces type errors (`string` is not a
			// known route id), so the rule cannot be satisfied type-safely for them. Static literal
			// links are still wrapped in `resolve()`; keep this as a warning so the guidance stays
			// visible without forcing untypable wraps or dozens of inline disables.
			'svelte/no-navigation-without-resolve': 'warn'
		}
	},
	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		languageOptions: {
			parserOptions: {
				// `.storybook/` sits outside SvelteKit's generated tsconfig `include`, so
				// its components have no project and the type-aware parser refuses them.
				// They are Storybook wiring, not app code, and typed-linting them buys
				// nothing.
				projectService: { allowDefaultProject: ['.storybook/*.svelte'] },
				extraFileExtensions: ['.svelte'],
				parser: ts.parser,
				svelteConfig
			}
		}
	},
	{
		// Register the custom plugin once, globally; the blocks below only enable rules.
		plugins: { custom: customPlugin }
	},
	{
		files: ['**/+page.svelte'],
		rules: { 'custom/no-raw-form-elements': 'warn', 'custom/no-utility-soup': 'warn' }
	},
	{
		files: ['**/*.svelte'],
		rules: { 'custom/no-duplicate-field-names': 'error' }
	},
	{
		files: ['src/lib/server/**/*.ts'],
		ignores: ['**/*.spec.ts'],
		rules: { 'custom/no-db-transaction': 'error' }
	}
);
