// For more info, see https://github.com/storybookjs/eslint-plugin-storybook#configuration-flat-config-format
import storybook from 'eslint-plugin-storybook';
import noRawFormElements from './eslint-rules/no-raw-form-elements.js';
import noUtilitySoup from './eslint-rules/no-utility-soup.js';
import noDuplicateFieldNames from './eslint-rules/no-duplicate-field-names.js';
import noDbTransaction from './eslint-rules/no-db-transaction.js';
import noConcurrentRemoteQueries from './eslint-rules/no-concurrent-remote-queries.js';
import refreshTheComposedQuery from './eslint-rules/refresh-the-composed-query.js';
import noDomainImportsInUi from './eslint-rules/no-domain-imports-in-ui.js';
import noContactSchemaImports from './eslint-rules/no-contact-schema-imports.js';

import prettier from 'eslint-config-prettier';
import path from 'node:path';
import { includeIgnoreFile } from '@eslint/compat';
import js from '@eslint/js';
import svelte from 'eslint-plugin-svelte';
import { defineConfig } from 'eslint/config';
import globals from 'globals';
import ts from 'typescript-eslint';
import svelteConfig from './svelte.config.js';

const gitignorePath = path.resolve(import.meta.dirname, '.gitignore');

// The `custom` plugin must be registered in exactly one config object — eslint's
// flat config rejects the same plugin namespace appearing in more than one config
// ("Cannot redefine plugin custom"), even with an identical object. So register it
// globally here and let the file-scoped blocks below only *enable* its rules.
const customPlugin = {
	rules: {
		'no-raw-form-elements': noRawFormElements,
		'no-utility-soup': noUtilitySoup,
		'no-duplicate-field-names': noDuplicateFieldNames,
		'no-db-transaction': noDbTransaction,
		'no-concurrent-remote-queries': noConcurrentRemoteQueries,
		'refresh-the-composed-query': refreshTheComposedQuery,
		'no-domain-imports-in-ui': noDomainImportsInUi,
		'no-contact-schema-imports': noContactSchemaImports
	}
};

export default defineConfig(
	includeIgnoreFile(gitignorePath),
	// Generated by `wrangler types` — not authored source, ships with its own /* eslint-disable */.
	{ ignores: ['worker-configuration.d.ts'] },
	js.configs.recommended,
	ts.configs.recommended,
	svelte.configs.recommended,
	// @ts-expect-error -- eslint-plugin-storybook still ships ESLint 9 `RuleModule`
	// types, which ESLint 10's `Plugin` no longer structurally accepts (its
	// `RuleContext` dropped `parserOptions`, `getAncestors` and friends). Runtime is
	// unaffected; drop this line when the plugin publishes ESLint 10 types.
	storybook.configs['flat/recommended'],
	prettier,
	svelte.configs.prettier,
	{
		languageOptions: { globals: { ...globals.browser, ...globals.node } },
		rules: {
			// typescript-eslint strongly recommend that you do not use the no-undef lint rule on TypeScript projects.
			// see: https://typescript-eslint.io/troubleshooting/faqs/eslint/#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors
			'no-undef': 'off',
			// Downgraded from the typescript-eslint recommended default (error) so the remaining
			// `any` usages stay visible without blocking CI, to be paid down incrementally. See
			// the override below for why test files are exempt rather than counted.
			'@typescript-eslint/no-explicit-any': 'warn',
			// Honour the conventional `_`-prefix for intentionally-unused bindings (e.g.
			// `{#each items as _, i}`, unused catch params). The rule still errors on all
			// other unused identifiers.
			'@typescript-eslint/no-unused-vars': [
				'error',
				{ argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }
			],
			// Error, not warn — the rule IS satisfiable, which the note it used to carry
			// got wrong. It is type-aware: `expressionIsAllowedType` accepts any
			// expression whose type is structurally `ResolvedPathname` from
			// `$app/types`. So a shared component that takes a route as a prop types
			// it `ResolvedPathname` rather than `string`, and the obligation moves to
			// the caller, which is the one place that actually holds the route
			// literal. (`Pathname` does not work — the rule tests assignability in
			// both directions and `Pathname` is a strict subtype.)
			//
			// `ignoreGoto` / `ignoreReplaceState` are the genuine exemptions. Links get
			// `allowAbsolute`, `allowFragment` and `allowNullish`, but `goto()` and
			// `replaceState()` get no allowances at all, and this app's list pages
			// navigate by rebuilding `page.url` with new search params — a resolved
			// route with a query string appended, which has no route id to resolve as
			// a whole. See docs/development/template-audit.md.
			'svelte/no-navigation-without-resolve': [
				'error',
				{ ignoreGoto: true, ignoreReplaceState: true }
			]
		}
	},
	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		languageOptions: {
			parserOptions: {
				// `.storybook/` sits outside SvelteKit's generated tsconfig `include`, so
				// its components have no project and the type-aware parser refuses them.
				// They are Storybook wiring, not app code, and typed-linting them buys
				// nothing.
				projectService: { allowDefaultProject: ['.storybook/*.svelte'] },
				extraFileExtensions: ['.svelte'],
				parser: ts.parser,
				svelteConfig
			}
		}
	},
	{
		// Register the custom plugin once, globally; the blocks below only enable rules.
		plugins: { custom: customPlugin }
	},
	{
		// `no-explicit-any` exists to pay down `any` in *shipped* code. It has no purchase on a
		// test double: the dominant shape here is
		// `vi.mocked(db.select).mockReturnValue({ from } as any)` — a one-method stub cast to
		// drizzle's full query-builder chain type, which is not expressible in less code than the
		// test itself. Measured at 5b45863: 428 warnings, of which 377 were tests/scripts/e2e and
		// only 51 were production source. The 377 buried the 51 well enough that the count grew
		// from ~200 to 428 unnoticed, so the number had stopped meaning anything.
		//
		// This is bookkeeping, not a safety gain — it silences warnings rather than typing
		// anything. It is narrow, though: `vi.mocked(db.select)` stays typed, and only the mock's
		// *return shape* is cast, so a signature change in the code under test still fails.
		files: ['**/*.spec.ts', '**/*.test.ts', 'scripts/**', 'e2e/**'],
		rules: { '@typescript-eslint/no-explicit-any': 'off' }
	},
	{
		// The Form boundary applies to every theme, so this one keeps its full reach.
		files: ['**/+page.svelte'],
		rules: { 'custom/no-raw-form-elements': 'warn' }
	},
	{
		// `band-site/` is a separate theme context with its own token set
		// (`src/lib/themes/band-site/index.css`) and deliberately neutral print-style
		// greys, so the app's components and semantic utilities are the wrong target
		// for it. template-audit.md has declared it out of scope since Phase 1; this
		// is that decision written where the rule can read it.
		files: ['**/+page.svelte'],
		ignores: ['src/routes/band-site/**'],
		rules: { 'custom/no-utility-soup': 'warn' }
	},
	{
		files: ['**/*.svelte'],
		rules: {
			'custom/no-duplicate-field-names': 'error',
			'custom/no-concurrent-remote-queries': 'error'
		}
	},
	{
		files: ['src/lib/remote/**/*.remote.ts'],
		rules: { 'custom/refresh-the-composed-query': 'error' }
	},
	{
		files: ['src/lib/server/**/*.ts'],
		ignores: ['**/*.spec.ts'],
		rules: { 'custom/no-db-transaction': 'error' }
	},
	{
		// components/ui/ is the design system — primitives only, no domain knowledge.
		// Stories and specs are allowed to reach for fixtures the primitive itself cannot.
		files: ['src/lib/components/ui/**/*.{ts,svelte}'],
		ignores: ['**/*.spec.ts', '**/*.stories.svelte'],
		rules: { 'custom/no-domain-imports-in-ui': 'error' }
	},
	{
		// config.ts is the shared client/server vocabulary: 206 files import it
		// and 88 of them are `.svelte`, so anything it pulls in lands in the
		// browser bundle. The capability matrix lives there; the access
		// controller that evaluates it (`createAccessControl`) is built in
		// `src/lib/server/authorization.ts` precisely so better-auth stays out
		// of the client. A comment alone would not survive the first person who
		// finds it convenient to build the controller beside the matrix.
		files: ['src/lib/config.ts'],
		rules: {
			'no-restricted-imports': 'off',
			// The typescript-eslint variant, for `allowTypeImports`: a type-only
			// import emits nothing, and config.ts already has one
			// (`import type { CreditType }`) that is perfectly safe.
			'@typescript-eslint/no-restricted-imports': [
				'error',
				{
					patterns: [
						{
							group: ['better-auth', 'better-auth/*', '$lib/server', '$lib/server/*'],
							allowTypeImports: true,
							message:
								'config.ts is client-bundled. Build server-only things (the access controller, db access) in $lib/server instead.'
						}
					]
				}
			]
		}
	},
	{
		// The private contact table has one access path. Unlike the rules above,
		// this one is deliberately NOT scoped to a folder and does NOT exempt
		// specs: the whole point is that no file anywhere reaches the table except
		// the service that guards it, and a spec that imported it directly would
		// be demonstrating exactly the leak the boundary exists to prevent. The
		// rule keeps its own allow-list.
		files: ['**/*.{ts,svelte}'],
		rules: { 'custom/no-contact-schema-imports': 'error' }
	}
);
