// For more info, see https://github.com/storybookjs/eslint-plugin-storybook#configuration-flat-config-format
import storybook from 'eslint-plugin-storybook';
import noRawFormElements from './eslint-rules/no-raw-form-elements.js';
import noUtilitySoup from './eslint-rules/no-utility-soup.js';
import noDuplicateFieldNames from './eslint-rules/no-duplicate-field-names.js';
import noDbTransaction from './eslint-rules/no-db-transaction.js';
import noConcurrentRemoteQueries from './eslint-rules/no-concurrent-remote-queries.js';
import refreshTheComposedQuery from './eslint-rules/refresh-the-composed-query.js';

import prettier from 'eslint-config-prettier';
import path from 'node:path';
import { includeIgnoreFile } from '@eslint/compat';
import js from '@eslint/js';
import svelte from 'eslint-plugin-svelte';
import { defineConfig } from 'eslint/config';
import globals from 'globals';
import ts from 'typescript-eslint';
import svelteConfig from './svelte.config.js';

const gitignorePath = path.resolve(import.meta.dirname, '.gitignore');

// The `custom` plugin must be registered in exactly one config object — eslint's
// flat config rejects the same plugin namespace appearing in more than one config
// ("Cannot redefine plugin custom"), even with an identical object. So register it
// globally here and let the file-scoped blocks below only *enable* its rules.
const customPlugin = {
	rules: {
		'no-raw-form-elements': noRawFormElements,
		'no-utility-soup': noUtilitySoup,
		'no-duplicate-field-names': noDuplicateFieldNames,
		'no-db-transaction': noDbTransaction,
		'no-concurrent-remote-queries': noConcurrentRemoteQueries,
		'refresh-the-composed-query': refreshTheComposedQuery
	}
};

export default defineConfig(
	includeIgnoreFile(gitignorePath),
	// Generated by `wrangler types` — not authored source, ships with its own /* eslint-disable */.
	{ ignores: ['worker-configuration.d.ts'] },
	js.configs.recommended,
	ts.configs.recommended,
	svelte.configs.recommended,
	storybook.configs['flat/recommended'],
	prettier,
	svelte.configs.prettier,
	{
		languageOptions: { globals: { ...globals.browser, ...globals.node } },
		rules: {
			// typescript-eslint strongly recommend that you do not use the no-undef lint rule on TypeScript projects.
			// see: https://typescript-eslint.io/troubleshooting/faqs/eslint/#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors
			'no-undef': 'off',
			// Downgraded from the typescript-eslint recommended default (error) so the remaining
			// `any` usages stay visible without blocking CI, to be paid down incrementally. See
			// the override below for why test files are exempt rather than counted.
			'@typescript-eslint/no-explicit-any': 'warn',
			// Honour the conventional `_`-prefix for intentionally-unused bindings (e.g.
			// `{#each items as _, i}`, unused catch params). The rule still errors on all
			// other unused identifiers.
			'@typescript-eslint/no-unused-vars': [
				'error',
				{ argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }
			],
			// Downgraded from svelte recommended (error). SvelteKit's typed `resolve()` only accepts
			// statically-known route ids, but this codebase navigates to many runtime/dynamic string
			// paths (generic `href` props on Nav/Button/IdCard/etc., remote `redirectUrl`s, computed
			// nav targets). Wrapping those in `resolve()` produces type errors (`string` is not a
			// known route id), so the rule cannot be satisfied type-safely for them. Static literal
			// links are still wrapped in `resolve()`; keep this as a warning so the guidance stays
			// visible without forcing untypable wraps or dozens of inline disables.
			'svelte/no-navigation-without-resolve': 'warn'
		}
	},
	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		languageOptions: {
			parserOptions: {
				// `.storybook/` sits outside SvelteKit's generated tsconfig `include`, so
				// its components have no project and the type-aware parser refuses them.
				// They are Storybook wiring, not app code, and typed-linting them buys
				// nothing.
				projectService: { allowDefaultProject: ['.storybook/*.svelte'] },
				extraFileExtensions: ['.svelte'],
				parser: ts.parser,
				svelteConfig
			}
		}
	},
	{
		// Register the custom plugin once, globally; the blocks below only enable rules.
		plugins: { custom: customPlugin }
	},
	{
		// `no-explicit-any` exists to pay down `any` in *shipped* code. It has no purchase on a
		// test double: the dominant shape here is
		// `vi.mocked(db.select).mockReturnValue({ from } as any)` — a one-method stub cast to
		// drizzle's full query-builder chain type, which is not expressible in less code than the
		// test itself. Measured at 5b45863: 428 warnings, of which 377 were tests/scripts/e2e and
		// only 51 were production source. The 377 buried the 51 well enough that the count grew
		// from ~200 to 428 unnoticed, so the number had stopped meaning anything.
		//
		// This is bookkeeping, not a safety gain — it silences warnings rather than typing
		// anything. It is narrow, though: `vi.mocked(db.select)` stays typed, and only the mock's
		// *return shape* is cast, so a signature change in the code under test still fails.
		files: ['**/*.spec.ts', '**/*.test.ts', 'scripts/**', 'e2e/**'],
		rules: { '@typescript-eslint/no-explicit-any': 'off' }
	},
	{
		files: ['**/+page.svelte'],
		rules: { 'custom/no-raw-form-elements': 'warn', 'custom/no-utility-soup': 'warn' }
	},
	{
		files: ['**/*.svelte'],
		rules: {
			'custom/no-duplicate-field-names': 'error',
			'custom/no-concurrent-remote-queries': 'error'
		}
	},
	{
		files: ['src/lib/remote/**/*.remote.ts'],
		rules: { 'custom/refresh-the-composed-query': 'error' }
	},
	{
		files: ['src/lib/server/**/*.ts'],
		ignores: ['**/*.spec.ts'],
		rules: { 'custom/no-db-transaction': 'error' }
	}
);
