/**
 * Emit `financial_entry` rows for every historical Stripe charge.
 *
 * SQL to a file rather than a direct write, so what lands in the ledger can
 * be read before it does. #825 phase 3.
 *
 *   pnpm tsx scripts/db/backfill/stripe-entries.ts > /tmp/stripe.sql
 */

import 'dotenv/config';
import Stripe from 'stripe';

const key = process.env.STRIPE_SECRET_KEY;
if (!key) {
	console.error('STRIPE_SECRET_KEY is not set.');
	process.exit(1);
}
const stripe = new Stripe(key);

/** The collective's share of a ticket. Confirmed: it has only ever been 30%. */
const COLLECTIVE_BPS = 3000;
/** Half an hour at the $15 room rate. Confirmed: the rate has never moved. */
const HALF_HOUR_CENTS = 750;

type Bucket = 'membership' | 'ticket' | 'reservation' | 'other';

/**
 * What a charge was for.
 *
 * Metadata first: it is what the app itself wrote. The fallback is the
 * room-rate ladder — a charge with no metadata that is an exact multiple of
 * half an hour at $15 is room time, which covers 24 of the 25 strays.
 */
function bucketOf(c: Stripe.Charge): Bucket {
	const m = c.metadata ?? {};
	if (m.purchase_id || m.ticket_order_id || m.ticket_quantity) return 'ticket';
	if (m.reservation_id) return 'reservation';
	const d = c.description ?? '';
	if (d.includes('Subscription') || d.includes('Invoice')) return 'membership';
	if (c.amount % HALF_HOUR_CENTS === 0) return 'reservation';
	return 'other';
}

const q = (s: string | null | undefined) => (s == null ? 'NULL' : `'${s.replace(/'/g, "''")}'`);

type Row = {
	amount: number;
	kind: string;
	category: string;
	settlement: string;
	subjectType: string;
	subjectId: string;
	group?: string | null;
	description: string;
};

function rowsFor(c: Stripe.Charge): Row[] {
	const m = c.metadata ?? {};
	const b = bucketOf(c);

	if (b === 'ticket') {
		const collective = Math.round((c.amount * COLLECTIVE_BPS) / 10_000);
		const acts = c.amount - collective;
		const id = m.purchase_id || m.ticket_order_uuid || m.ticket_order_id || recordId(c);
		return [
			{
				amount: collective,
				kind: 'earned',
				category: 'ticket_sales',
				settlement: 'stripe',
				subjectType: 'ticket',
				subjectId: id,
				description: 'Ticket sale (backfilled from Stripe)'
			},
			// The out-leg is written when settlement pays the act, which is not
			// built — so these sit as an open pool, deliberately.
			{
				amount: acts,
				kind: 'pass_through',
				category: 'act_payout',
				settlement: 'stripe',
				subjectType: 'ticket',
				subjectId: `${id}:acts`,
				group: m.event_id ?? null,
				description: "Acts' share (backfilled from Stripe)"
			}
		];
	}

	if (b === 'reservation') {
		return [
			{
				amount: c.amount,
				kind: 'earned',
				category: 'reservation',
				settlement: 'stripe',
				subjectType: 'reservation',
				subjectId: m.reservation_id || recordId(c),
				description: 'Practice room (backfilled from Stripe)'
			}
		];
	}

	return [
		{
			amount: c.amount,
			kind: 'earned',
			category: b === 'membership' ? 'membership' : 'other',
			settlement: 'stripe',
			subjectType: b === 'membership' ? 'membership' : 'other',
			subjectId: recordId(c),
			description: `${b === 'membership' ? 'Membership' : 'Uncategorised'} (backfilled from Stripe)`
		}
	];
}

/**
 * The id the app itself records, which is the PaymentIntent and not the
 * charge. Keying on the charge id instead double-counted a sale the live
 * writer had already captured: same payment, two identifiers, so neither
 * guard matched and the fee row it writes was invisible.
 */
const recordId = (c: Stripe.Charge) =>
	typeof c.payment_intent === 'string' ? c.payment_intent : (c.payment_intent?.id ?? c.id);

const charges: Stripe.Charge[] = [];
for await (const c of stripe.charges.list({ limit: 100 })) charges.push(c);

const out: string[] = [
	'-- Generated by scripts/db/backfill/stripe-entries.ts. Do not hand-edit.',
	`-- ${charges.length} charges read from Stripe on ${new Date().toISOString().slice(0, 10)}.`,
	'--',
	'-- Idempotent: every insert is guarded on the charge id, which no two rows',
	'-- share, so a second run writes nothing. The live checkout writer records',
	'-- the same id, so anything it already wrote is skipped rather than doubled.',
	''
];

let written = 0;
let refunds = 0;
for (const c of charges) {
	if (c.status !== 'succeeded') continue;
	for (const r of rowsFor(c)) {
		out.push(
			`INSERT INTO financial_entry (id, amount_cents, kind, category, occurred_at, settlement,` +
				` stripe_payment_record_id, settlement_group, subject_type, subject_id, user_id,` +
				` description, metadata, created_at)\nSELECT lower(hex(randomblob(16))), ${r.amount},` +
				` ${q(r.kind)}, ${q(r.category)}, ${c.created}, ${q(r.settlement)}, ${q(recordId(c))},` +
				` ${q(r.group ?? null)}, ${q(r.subjectType)}, ${q(r.subjectId)}, NULL, ${q(r.description)},` +
				` json_object('backfilled', json('true'), 'source', 'stripe'), unixepoch()\n` +
				`WHERE NOT EXISTS (SELECT 1 FROM financial_entry e WHERE e.stripe_payment_record_id = ${q(recordId(c))}` +
				` AND e.subject_id = ${q(r.subjectId)})\n` +
				// The live checkout writer records the same charge id. If it already
				// did, this charge is history the app captured properly and must not
				// be reconstructed on top of — it writes a fee row this cannot see.
				`  AND NOT EXISTS (SELECT 1 FROM financial_entry l WHERE l.stripe_payment_record_id = ${q(recordId(c))}` +
				` AND COALESCE(json_extract(l.metadata, '$.source'), '') <> 'stripe');`
		);
		written++;
	}

	// A refund is a reversing entry, never a mutation — the spec's first rule
	// for a writer, and $184.51 has been refunded historically.
	if (c.amount_refunded > 0) {
		out.push(
			`INSERT INTO financial_entry (id, amount_cents, kind, category, occurred_at, settlement,` +
				` stripe_payment_record_id, subject_type, subject_id, description, metadata, created_at)\n` +
				`SELECT lower(hex(randomblob(16))), ${-c.amount_refunded}, 'earned', 'refund_absorbed',` +
				` ${c.created}, 'stripe', ${q(recordId(c))}, 'other', ${q(recordId(c) + ':refund')},` +
				` 'Refund (backfilled from Stripe)', json_object('backfilled', json('true'), 'source', 'stripe'), unixepoch()\n` +
				`WHERE NOT EXISTS (SELECT 1 FROM financial_entry e WHERE e.subject_id = ${q(recordId(c) + ':refund')});`
		);
		refunds++;
	}
}

console.log(out.join('\n\n'));
console.error(
	`${written} entry rows and ${refunds} refund reversals from ${charges.length} charges.`
);
