/**
 * Every source file in the repo is compiled by something.
 *
 * This is the guard that would have caught the hole #536 closed. `pnpm check`
 * runs svelte-check against the generated `.svelte-kit/tsconfig.json`, whose
 * `include` is `src`, `test`, `tests` and two config files — so `scripts/` and
 * `e2e/` (14,583 lines, against the real schema) were compiled by nothing at
 * all, and had been for as long as they had existed. Nobody removed them from a
 * gate; they were simply never added to one, and no gate can notice its own
 * absence.
 *
 * So: enumerate the files, enumerate what the tsconfigs claim, and fail on the
 * difference. A new top-level directory is now a failing test rather than a
 * silent gap.
 *
 * This checks the *declared* coverage — the `include` globs — not what `tsc`
 * ends up loading. That is deliberate: a file pulled in only because something
 * else imports it is not covered in any useful sense, because deleting that
 * import would drop it back out without a word.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { globSync } from 'node:fs';

const ROOT = new URL('../', import.meta.url);

/** Source extensions worth compiling. Anything here must land in some project. */
const SOURCE_GLOB = '**/*.{ts,mts,cts,js,mjs,cjs,svelte}';

const IGNORED = [
	'node_modules/**',
	'.svelte-kit/**',
	'build/**',
	'dist/**',
	'.wrangler/**',
	'coverage/**',
	'storybook-static/**'
];

/**
 * Files that are deliberately outside every project, each for a stated reason.
 * Keep this list short and keep the reasons true — it is the escape hatch, and
 * an escape hatch nobody can read is just a hole with extra steps.
 */
const EXEMPT: Record<string, string> = {
	// Generated by `wrangler types`, gitignored by prettier and eslint too, and
	// stale besides (it names `corvmc_db`; wrangler.toml says `DB`).
	'worker-configuration.d.ts': 'generated by wrangler types',
	// SvelteKit's own ambient shims for the vitest browser mode.
	'vitest.shims.d.ts': 'ambient shims, no code',
	// Cannot be typechecked without building first: it imports
	// `.svelte-kit/cloudflare/_worker.js`, which the adapter only writes during
	// `pnpm build`, and the check job deliberately does not build. Its own header
	// says so. The `scheduled` handler it adds is 28 lines and fully JSDoc'd.
	'worker.js': 'imports a build artifact that does not exist at check time'
};

/** tsconfig files are JSONC — strip comments before parsing. */
function readJsonc(path: string): { include?: string[]; exclude?: string[] } {
	const raw = readFileSync(new URL(path, ROOT), 'utf8');
	return JSON.parse(raw.replace(/^\s*\/\/.*$/gm, ''));
}

/**
 * A tsconfig `include` entry as a matcher, resolved relative to the directory
 * holding the config. The generated config lives in `.svelte-kit/`, so its
 * globs read `../src/**` and have to be normalised against the repo root.
 */
function globsOf(configPath: string): string[] {
	const dir = configPath.includes('/') ? configPath.slice(0, configPath.lastIndexOf('/') + 1) : '';
	return (readJsonc(configPath).include ?? []).map((pattern) => {
		const joined = `${dir}${pattern}`;
		// Collapse a single leading `../` that points back at the repo root.
		return joined.replace(/^[^/]+\/\.\.\//, '');
	});
}

const PROJECTS = ['tsconfig.tooling.json', '.svelte-kit/tsconfig.json'];

function sourceFiles(): string[] {
	return globSync(SOURCE_GLOB, { cwd: ROOT, exclude: IGNORED }).map((p) => p.replaceAll('\\', '/'));
}

function coveredFiles(): Set<string> {
	const covered = new Set<string>();
	for (const project of PROJECTS) {
		for (const pattern of globsOf(project)) {
			for (const file of globSync(pattern, { cwd: ROOT, exclude: IGNORED })) {
				covered.add(file.replaceAll('\\', '/'));
			}
		}
	}
	return covered;
}

describe('typecheck coverage', () => {
	it('has a generated tsconfig to read', () => {
		// `svelte-kit sync` writes it; `pnpm install` runs that through `prepare`.
		// Without this the whole suite below would pass vacuously.
		expect(globsOf('.svelte-kit/tsconfig.json').length).toBeGreaterThan(0);
	});

	it('compiles every source file in some project', () => {
		const covered = coveredFiles();
		const uncovered = sourceFiles()
			.filter((file) => !covered.has(file))
			.filter((file) => !(file in EXEMPT));

		expect(
			uncovered,
			'add these to `tsconfig.tooling.json` (or to EXEMPT here, with a reason)'
		).toEqual([]);
	});

	it('keeps the exemption list honest', () => {
		// An exemption for a file that no longer exists reads as considered
		// judgement when it is just debris.
		const present = new Set(sourceFiles());
		const stale = Object.keys(EXEMPT).filter((file) => !present.has(file));

		expect(stale, 'these are exempt from a check they no longer need').toEqual([]);
	});
});

describe('test discovery', () => {
	it('has no `.test.ts` files', () => {
		// The vitest project globs match `.spec` only, so a `.test.ts` is a file
		// full of assertions that nothing ever runs — the failure mode being that
		// it looks exactly like passing.
		const misnamed = globSync('**/*.test.{ts,js,svelte.ts}', { cwd: ROOT, exclude: IGNORED });

		expect(misnamed, 'rename to `.spec.ts` — the vitest globs do not match `.test`').toEqual([]);
	});

	it('keeps every spec under a root some vitest project scans', () => {
		// `src/`, `scripts/` and `e2e/` are the three include roots in
		// vite.config.ts. A spec outside them is the same silent no-op.
		const stranded = globSync('**/*.spec.{ts,js}', { cwd: ROOT, exclude: IGNORED })
			.map((p) => p.replaceAll('\\', '/'))
			.filter((file) => !/^(src|scripts|e2e)\//.test(file));

		expect(stranded, 'no vitest project includes these').toEqual([]);
	});
});
